services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=weather_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=12345
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - OWM_API_KEY=

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
